services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: hungnp25-db
    environment:
      - POSTGRES_USER=hungnp25
      - POSTGRES_PASSWORD=hungnp25
      - POSTGRES_DB=hungnp25_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data